'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>  _
Partial Friend NotInheritable Class progset
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As progset = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New progset()),progset)
    
    Public Shared ReadOnly Property [Default]() As progset
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Auto")>  _
    Public Property ProgColMode() As String
        Get
            Return CType(Me("ProgColMode"),String)
        End Get
        Set
            Me("ProgColMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("WIMR")>  _
    Public Property InstCreateMode() As String
        Get
            Return CType(Me("InstCreateMode"),String)
        End Get
        Set
            Me("InstCreateMode") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property UseBIOSPTCompat() As Boolean
        Get
            Return CType(Me("UseBIOSPTCompat"),Boolean)
        End Get
        Set
            Me("UseBIOSPTCompat") = value
        End Set
    End Property
End Class
