'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Windows_11_Manual_Installer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property automatic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("automatic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_arrow_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_arrow_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_arrow_disabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_arrow_disabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blackPanelBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blackPanelBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bloom_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bloom_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bloom_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bloom_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property build_mode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("build_mode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property checkBoxTBSwitch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkBoxTBSwitch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closebox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closebox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closebox_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closebox_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closebox_dark_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closebox_dark_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closebox_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closebox_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closebox_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closebox_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property colormodes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("colormodes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comp_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comp_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property comp_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comp_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property components() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("components", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property context() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("context", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property csvfile_cms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("csvfile_cms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property darkmode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("darkmode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property debug_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("debug_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property debug_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("debug_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dllr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dllr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dllr_mh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dllr_mh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property export_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property export_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("export_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_create_fluent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_create_fluent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_download_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_download_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_download_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_download_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_fluent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_fluent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property first_step_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("first_step_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property functionality() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("functionality", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property functionality_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("functionality_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property functionality_icon_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("functionality_icon_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_dark_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_dark_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property help_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property helpbanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helpbanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property helpbanner_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helpbanner_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_dark_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_dark_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property home_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property htmlfile_cms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("htmlfile_cms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hummingbird() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hummingbird", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hummingbird_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hummingbird_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property icon3() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon3", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_dark_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_dark_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_create() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_create", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_create_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_create_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_create_dark_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_create_dark_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_create_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_create_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst_hist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst_hist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instructions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instructions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instructions_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instructions_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instructions_dark_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instructions_dark_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property instructions_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("instructions_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property isofile_optn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("isofile_optn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property language() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("language", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property last_step_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("last_step_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lightmode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lightmode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property linux_ua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("linux_ua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log_del() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_del", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log_del_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log_del_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_wide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_wide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxbox_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxbox_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxbox_dark_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxbox_dark_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxbox_dark_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxbox_dark_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxbox_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxbox_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxbox_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxbox_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minBox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minBox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minBox_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minBox_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minBox_dark_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minBox_dark_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minBox_dark_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minBox_dark_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minBox_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minBox_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minBox_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minBox_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property miniMode_TBRes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("miniMode_TBRes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavBar_LeftPos_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBar_LeftPos_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavBar_LeftPos_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBar_LeftPos_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavBar_TopPos_Dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBar_TopPos_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NavBar_TopPos_Light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NavBar_TopPos_Light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_step_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_step_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property NotifyIconRes_Dark() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyIconRes_Dark", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        '''</summary>
        Friend ReadOnly Property NotifyIconRes_Light() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("NotifyIconRes_Light", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_corner_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_corner_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_corner_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_corner_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_indicator_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_indicator_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_indicator_dark_top_navbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_indicator_dark_top_navbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_indicator_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_indicator_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_indicator_light_top_navbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel_indicator_light_top_navbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property personalization() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personalization", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property personalization_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personalization_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property personalization_icon_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personalization_icon_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pref_reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pref_reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pref_reset_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pref_reset_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prev_step_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev_step_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property progressring_indeterminate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressring_indeterminate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question_mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property regtweak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regtweak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property regtweak_mh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("regtweak_mh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restdownbox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restdownbox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restdownbox_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restdownbox_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restdownbox_dark_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restdownbox_dark_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restdownbox_dark_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restdownbox_dark_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restdownbox_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restdownbox_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property restdownbox_focus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("restdownbox_focus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_dark_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_dark_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settings_filled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_filled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tb_Black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb_Black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tb_White() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb_White", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property topnavbar_x86_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topnavbar_x86_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property topnavbar_x86_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("topnavbar_x86_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property unknown_drive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unknown_drive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_screen_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_screen_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property update_screen_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_screen_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property whitePanelBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whitePanelBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wimr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wimr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wimr_mh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wimr_mh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win10inst_pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win10inst_pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Win11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Win11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11inst_pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11inst_pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_7z_dllr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_7z_dllr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_7z_regtweak() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_7z_regtweak", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_7z_wimr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_7z_wimr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_7zipdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_7zipdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_advoptn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_advoptn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_advoptn_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_advoptn_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_darkmode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_darkmode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_functionality() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_functionality", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_functionality_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_functionality_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_help_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_help_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_info_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_info_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_instcreate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_instcreate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_instcreate_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_instcreate_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_instcreateproc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_instcreateproc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_instcreateproc_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_instcreateproc_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_instfinish() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_instfinish", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_instfinish_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_instfinish_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_insthist() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_insthist", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_insthist_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_insthist_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_isofilebuild() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_isofilebuild", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_isofiledown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_isofiledown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_isofiledown_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_isofiledown_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_isofilescan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_isofilescan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_lightmode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_lightmode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_mainscr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_mainscr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_mainscr_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_mainscr_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_oscdimg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_oscdimg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_settingreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_settingreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_settingreview_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_settingreview_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_settings_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_settings_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_sidepanelhover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_sidepanelhover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_topnavbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_topnavbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_topnavbar_dm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_topnavbar_dm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_w10instdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_w10instdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_w11instdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_w11instdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_win11install() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_win11install", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property win11minst_workdir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win11minst_workdir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wmi_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wmi_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x86_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x86_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property x86_light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("x86_light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property xmlfile_cms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xmlfile_cms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
